CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    email       VARCHAR(160) NOT NULL UNIQUE,
    senha_hash  VARCHAR(100) NOT NULL,
    perfil      VARCHAR(20)  NOT NULL,
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE empresas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social    VARCHAR(200) NOT NULL,
    nome_fantasia   VARCHAR(200),
    cnpj            VARCHAR(14) UNIQUE,
    segmento        VARCHAR(100),
    porte           VARCHAR(20),
    cidade          VARCHAR(100),
    uf              VARCHAR(2),
    site            VARCHAR(200),
    telefone        VARCHAR(30),
    email           VARCHAR(160),
    origem          VARCHAR(100),
    etapa           VARCHAR(20)  NOT NULL,
    valor_estimado  NUMERIC(15, 2),
    motivo_perda    VARCHAR(500),
    observacoes     VARCHAR(4000),
    responsavel_id  BIGINT REFERENCES usuarios (id),
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_empresas_etapa ON empresas (etapa);
CREATE INDEX idx_empresas_responsavel ON empresas (responsavel_id);

CREATE TABLE contatos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  BIGINT NOT NULL REFERENCES empresas (id) ON DELETE CASCADE,
    nome        VARCHAR(120) NOT NULL,
    cargo       VARCHAR(100),
    email       VARCHAR(160),
    telefone    VARCHAR(30),
    linkedin    VARCHAR(200),
    principal   BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_contatos_empresa ON contatos (empresa_id);

CREATE TABLE interacoes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id           BIGINT NOT NULL REFERENCES empresas (id) ON DELETE CASCADE,
    contato_id           BIGINT REFERENCES contatos (id) ON DELETE SET NULL,
    usuario_id           BIGINT NOT NULL REFERENCES usuarios (id),
    tipo                 VARCHAR(20)   NOT NULL,
    descricao            VARCHAR(4000) NOT NULL,
    data_hora            TIMESTAMP WITH TIME ZONE NOT NULL,
    proximo_passo        VARCHAR(500),
    data_follow_up       TIMESTAMP WITH TIME ZONE,
    follow_up_concluido  BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em            TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_interacoes_empresa ON interacoes (empresa_id);
CREATE INDEX idx_interacoes_follow_up ON interacoes (data_follow_up);
